namespace WindowAPI.winnt.Enums
{


    public enum ACTCTX_COMPATIBILITY_ELEMENT_TYPE
    {
        ACTCTX_COMPATIBILITY_ELEMENT_TYPE_UNKNOWN = 0,
        ACTCTX_COMPATIBILITY_ELEMENT_TYPE_OS,
        ACTCTX_COMPATIBILITY_ELEMENT_TYPE_MITIGATION,
        ACTCTX_COMPATIBILITY_ELEMENT_TYPE_MAXVERSIONTESTED
    }



}

