global using System.Runtime.InteropServices;
global using System.Text;
global using WindowAPI.Af_irda.h.Structures;
global using WindowAPI.console.Structures;
global using WindowAPI.inaddr.h.Structures;
global using WindowAPI.Winbase.h.Structures;
global using WindowAPI.windef.Enums;
global using WindowAPI.windef.Structures;
global using WindowAPI.wingdi.Enums;
global using WindowAPI.wingdi.Structures;
global using WindowAPI.winnt.Enums;
global using WindowAPI.winnt.Structures;
global using static WindowAPI.wingdi.CallBacks.CallBacks;
global using static WindowAPI.winuser.CallBacks.CallBacks;
global using WindowAPI.mstcpip.Enums;
global using static WindowAPI.Winbase.h.CallBacks.CallBack;
