global using System.Runtime.InteropServices;
global using System.Text;
global using WindowAPI.console.Structures;
global using WindowAPI.Winbase.h.Structures;
global using WindowAPI.windef.Enums;
global using WindowAPI.windef.Structures;
global using WindowAPI.wingdi.Enums;
global using WindowAPI.wingdi.Structures;
global using WindowAPI.winnt.Enums;
global using WindowAPI.winnt.Structures;
global using WindowAPI.winuser.h.Enums;
global using WindowAPI.winuser.h.Structures;
global using static WindowAPI.winuser.CallBack.CallBacks;
global using static WindowAPI.wingdi.CallBacks.CallBacks;
