namespace WindowAPI.wingdi.Enums
{


    public enum DISPLAYCONFIG_TOPOLOGY_ID : uint
    {
        DISPLAYCONFIG_TOPOLOGY_INTERNAL = 00000001,
        DISPLAYCONFIG_TOPOLOGY_CLONE = 00000002,
        DISPLAYCONFIG_TOPOLOGY_EXTEND = 00000004,
        DISPLAYCONFIG_TOPOLOGY_EXTERNAL = 00000008,
        DISPLAYCONFIG_TOPOLOGY_FORCE_UINT32 = 0xFFFFFFFF
    }



}

