namespace WindowAPI.mstcpip.Enums
{


    public enum CONTROL_CHANNEL_TRIGGER_STATUS
    {
        CONTROL_CHANNEL_TRIGGER_STATUS_INVALID = 0,
        CONTROL_CHANNEL_TRIGGER_STATUS_SOFTWARE_SLOT_ALLOCATED = 1,
        CONTROL_CHANNEL_TRIGGER_STATUS_HARDWARE_SLOT_ALLOCATED = 2,
        CONTROL_CHANNEL_TRIGGER_STATUS_POLICY_ERROR = 3,
        CONTROL_CHANNEL_TRIGGER_STATUS_SYSTEM_ERROR = 4,
        CONTROL_CHANNEL_TRIGGER_STATUS_TRANSPORT_DISCONNECTED = 5,
        CONTROL_CHANNEL_TRIGGER_STATUS_SERVICE_UNAVAILABLE = 6
    }



}

