namespace WindowAPI.winuser.Enums
{


    public enum POINTER_DEVICE_CURSOR_TYPE : uint
    {
        POINTER_DEVICE_CURSOR_TYPE_UNKNOWN = 00000000,
        POINTER_DEVICE_CURSOR_TYPE_TIP = 00000001,
        POINTER_DEVICE_CURSOR_TYPE_ERASER = 00000002,
        POINTER_DEVICE_CURSOR_TYPE_MAX = 0xFFFFFFFF
    }



}

