namespace WindowAPI.winuser.h.Enums
{


    public enum POINTER_DEVICE_TYPE : uint
    {
        POINTER_DEVICE_TYPE_INTEGRATED_PEN = 00000001,
        POINTER_DEVICE_TYPE_EXTERNAL_PEN = 00000002,
        POINTER_DEVICE_TYPE_TOUCH = 00000003,
        POINTER_DEVICE_TYPE_TOUCH_PAD = 00000004,
        POINTER_DEVICE_TYPE_MAX = 0xFFFFFFFF
    }



}

